In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.cross_validation import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC

C:\Users\Cxovrika\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
# Grab just two categories from the 20 newsgroups dataset
#categories=['sci.space', 'rec.autos']

In [3]:
# Get training data
#ngd = fetch_20newsgroups(subset='train', categories=categories)
#X_train = ngd.data
#y_train = ngd.target

In [2]:
df_legitimate = pd.read_csv("legitimate_words.csv", header=None, encoding = 'utf8').dropna()
df_malicious = pd.read_csv("malicious_words.csv", header=None, encoding = 'utf8').dropna()
X_data = df_legitimate[0].tolist() + df_malicious[0].tolist()
y_data = np.zeros(len(df_legitimate)).tolist() + np.ones(len(df_malicious)).tolist()

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_data, y_data, test_size=0.2, random_state=42, shuffle = True)

In [4]:
cv_test = CountVectorizer()

In [5]:
x_traincv_test = cv_test.fit_transform(["Hi How are you How are you doing","Hi what's up","Wow that's awesome ttt/213s>2ss"])

In [6]:

x_traincv_test.toarray()

array([[0, 0, 2, 0, 1, 1, 2, 0, 0, 0, 0, 0, 2],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0],
       [1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0]], dtype=int64)

In [7]:
cv_test.get_feature_names()

['213s',
 '2ss',
 'are',
 'awesome',
 'doing',
 'hi',
 'how',
 'that',
 'ttt',
 'up',
 'what',
 'wow',
 'you']

In [8]:
cv = CountVectorizer()
x_traincv =cv.fit_transform(X_train)

In [9]:
len(cv.get_feature_names())

642133

In [10]:
x_traincv[0].toarray()

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [11]:
cv.inverse_transform(x_traincv[234].toarray())

[array(['5e5cd1c5bc5b2448b43d7f98e03a1812'], dtype='<U1026')]

In [12]:
x_testcv=cv.transform(X_test)

In [13]:
y_train= [int(i) for i in y_train]

In [81]:
type(y_train[1])

int

In [82]:
mnb = MultinomialNB()

In [84]:
mnb.fit(x_traincv, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [91]:
predictions=mnb.predict(x_testcv)

In [95]:
from sklearn.metrics import confusion_matrix

tn, fp, fn, tp = confusion_matrix(predictions, y_test).ravel()
print(tn, fp, fn, tp)
print((tn + tp) / (tn+fp+fn+tp))
print(tp / (tp + fn))
print((tp + fp) / (tn+fp+fn+tp))
print(tp / (tp+fp))
print(tn / (tn_fn))

258234 2079 638 7526
0.9898799524726513
0.9218520333170015
0.03577587651828648
0.7835502342529932


NameError: name 'tn_fn' is not defined

In [14]:

svm_model = LinearSVC()

In [15]:
svm_model.fit(x_traincv, y_train)


LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [17]:
predictions=svm_model.predict(x_testcv)

In [18]:
from sklearn.metrics import confusion_matrix

tn, fp, fn, tp = confusion_matrix(predictions, y_test).ravel()
print(tn, fp, fn, tp)
print((tn + tp) / (tn+fp+fn+tp))
print(tp / (tp + fn))
print((tp + fp) / (tn+fp+fn+tp))
print(tp / (tp+fp))
print(tn / (tn_fn))

258484 506 388 9099
0.9966701058191204
0.9591019289554127
0.03577587651828648
0.9473191046330036


NameError: name 'tn_fn' is not defined

In [10]:
from sklearn.svm import SVC

vectorizer = TfidfVectorizer(
    preprocessor=lambda x: map(str, x),
    tokenizer=lambda x: x,
    ngram_range=(1, 3))

model = Pipeline([('vectorizer', vectorizer), ('modelr', svm.SVC())])


In [13]:
print("SVM training started...")
clf = svm.SVC()

svm_model = clf.fit(X_train, y_train)
joblib.dump(svm_model, 'Models/svm.pkl')
print("SVM model saved into the disk")

SVM training started...


ValueError: could not convert string to float: 'javascript agent pem'

In [12]:
# Fit and assess training performance
model.fit(X_train, y_train)

TypeError: object of type 'map' has no len()

In [58]:
pred = pipeline_svm.predict(X_train)

In [59]:
from sklearn.metrics import confusion_matrix
print (confusion_matrix(pred, y_train))

[[1035658   38250]
 [      0       0]]


In [ ]:
#print("Classification accuracy on training data: %.2f" % pipeline.score(X_train, y_train))

In [60]:
# Performance on test data
#ngd = fetch_20newsgroups(subset='test', categories=categories)

test_predicitons = pipeline_svm.predict(X_test)
tn, fp, fn, tp = confusion_matrix(test_predicitons, y_test).ravel()
print(tn, fp, fn, tp)
print((tn + tp) / (tn+fp+fn+tp))
print(tp / (tp + fn))
print((tp + fp) / (tn+fp+fn+tp))
print(tp / (tp+fp))


#test_score = pipeline.score(ngd.data, ngd.target)
#print("Classification accuracy on test data: %.2f" % test_score)

258872 9605 0 0
0.9642241234817135
nan
0.03577587651828648
0.0


C:\Users\Cxovrika\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in longlong_scalars
  


In [44]:
pipeline.named_steps['classifier'].coef_[0]

array([8.9678836 , 7.57840911, 0.        , ..., 0.        , 0.        ,
       0.        ])

In [51]:
# Print largest coefficients
vec, clf = pipeline.named_steps['vectorizer'], pipeline.named_steps['classifier']
coefs = pd.Series(clf.coef_[0], index=vec.get_feature_names())
print("\n20 most discriminating words:")
print(coefs[coefs.sort_values(ascending=True).index][:20])


20 most discriminating words:
2fwindows       -67.308610
5cwindows       -56.661224
2008            -30.165285
level           -25.882050
u2215windows    -24.233155
0x3a            -22.887309
8080            -21.078458
2ewindows       -21.031018
indexer         -20.984757
ringtone        -20.078581
javascript      -19.884439
phpwebgallery   -18.154042
linpha          -16.710185
v1              -16.599212
weblinks        -16.448926
filhead         -16.397048
0x5cwindows     -16.024360
rush            -15.640784
loginname       -13.558606
disp            -13.382954
dtype: float64
